### PR TITLE
Fix issue in range checking for Switch.cpp

### PR DESCRIPTION
**Pull request by MacFurax**
Minor issue in range checking for Switch.cpp.

PR is full of other none relevent changes sorry for polution.

### CODE REVIEW

**Comment by npisanti** [comment]
please squash all the commit together and rebase, no way i can check the diff otherwise, it seems that there are too many things changed other than `Switch.cpp`

**Comment by MacFurax** [comment]
Ok I'll do that

Le jeu. 29 août 2019 à 11:03, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by npisanti** [comment]
thanks, let me know when it's ready so i can review it =)

**Comment by MacFurax** [comment]
Sure, I'm struggeling to make a clear branche with the changes....
I'll ask a colleage tomorrow, or I send you just the code ...

Le jeu. 29 août 2019 à 15:37, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by npisanti** [comment]
you can take it as exercise in git, but if you don't have the time, i can just take just the code from Switch.cpp, it looked fine to me ( i don't want to merge all the rest )

**Comment by MacFurax** [comment]
Yes I want to understand how to do it !
I have a similare issue with an other PR.
Please be patient :-)


Le ven. 30 août 2019 à 00:28, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by npisanti** [comment]
i have some memo for that, maybe i will write a quick howto someday.

Rebasing is useful to merge more commits together, i use interactive rebase ( `-i` ) option, so remember to close the text editor (you assigned to git) before starting, then for example
```
git rebase -i HEAD~4
```
to rebase the last 4 commits, leave one to `pick` and the other to `squash`, save and exit.
Now it will open anothe file in the text editor to change the messages, just leave a single message that will become the commit message.
Now rebase should be done, and you have to force push your branch:
```
git push -f 
```

you can see some pictures of the process here:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by npisanti** [comment]
as some time is passed and i needed to change some more code, i made a commit with your fixes, aknowledging you in the commit message, i hope this is fine 

thanks for helping!

**Comment by MacFurax** [comment]
Yes sure, it was the back to school weeks, so not much time to work on that
sorry !

Le ven. 13 sept. 2019 à 12:35, Nicola Pisanti <notifications@github.com> a
écrit :

**Pull request closed without merging**
