### PR TITLE
Added a getter for outputs

### PR DESCRIPTION
**Pull request by macramole**
We need to know the outputs of an OutputNode. This was a private member so we added a getter.

### CODE REVIEW

**Comment by npisanti** [comment]
hey! thanks for the PR, but you are returning by value, so the whole vector gets copied, i wouldn't merge that. 

I hope for you is fine to use a const reference to the vector, like this:
```cpp
const std::vector<pdsp::InputNode *> & pdsp::OutputNode::getOutputs() const
{
    return outputs;
}
```

**Comment by macramole** [comment]
voilá

**Comment by macramole** [comment]
uhmm i think atom did something to the file

**Comment by npisanti** [comment]
yes, i'd like a cleaner commit please 
( it seems it stripped some white space, i still have to run a proper formatter on all the ofxPDSP code but i will do it later in the future in a single commit )

**Comment by npisanti** [comment]
a 0.0f control-rate value should NOT trigger the process of any buffer, this is an important ofxPDSP design principle, stated in the README.md as "Lazy evaluated DSPs". Expecially into `pdsp::Amp` it saves many cpu cycles by avoid processing when the results should be 0.0f anyway.

**Comment by npisanti** [comment]
PS: this is a commit not related to the pull request topic, please open another separate pull request for separate features next time ( by the way as stated before, these kind of modification to `pdsp::Amp` won't be merged ).

**Comment by macramole** [comment]
Sorry, I didn't expect you to merge this. I added a new commit and it automatically appear here.

We have multiple samplers running at the same time. If we put Amp to 0.0 the playhead of the samplers get paused. Raising the volume to non-zero will cause all samples to be played at once. This is undesired and we didn't know how else to fix it. Thanks,

**Comment by npisanti** [comment]
with the actual behavior the samplers will be paused, but you want them to be muted, if you want to still work with something like amp the best thing would be to make a different unit for that.

Or if you just could choke the samples, after sending 0.0f to the amp you should send 1.0f to samplers `in_start()` and then trigger it to stop it ( you're basically saying to the sampler "trigger again from the end of the sample" ). When you have to trigger it again, send 0.0f to `in_start()` to set the starting point to the beginning again.

**Comment by macramole** [comment]
I'll make a new unit that is a clone of Amp but without the code I've commented. That way I won't lose compatibilty with the main project.

We are about to release 0.9.1 of AudioStellar using ofxPDSP as audio engine, thanks for your technical support.

**Comment by npisanti** [comment]
you're welcome!

**Pull request closed without merging**
