### PR TITLE
Notify engine of disconnected streams

### PR DESCRIPTION
**Pull request by nspotrepka**

### CODE REVIEW

**Comment by npisanti** [comment]
why is this needed?

**Comment by npisanti** [comment]
PS: i sent you a mail some time ago, have you seen it? i think we should find a better way to organize our efforts on ofxPDSP other than directly in the PR comments

**Comment by nspotrepka** [comment]
> why is this needed?

When your audio device gets disconnected and then you try to connect to another audio device, the program throws an error when trying to close a stream what was disconnected, so I avoid this error by checking (externally) if the audio device is gone, then notifying the engine to not try to close it.

Perhaps there is a more foolproof way of handling this, like checking the list of engines before closing the stream inside the Engine code itself.

**Comment by nspotrepka** [comment]
> PS: i sent you a mail some time ago, have you seen it? i think we should find a better way to organize our efforts on ofxPDSP other than directly in the PR comments

Yes, I did see your email. Some really good thoughts, and I try to incorporate these things into the development of my own project and of ofxPDSP. I'm writing some unit-based sequencing code that could be good for ofxPDSP once it's done.

I'm sort of just changing things as needed for my own project, and if I think the changes apply to ofxPDSP as a whole, then I try to format everything nicely and submit a pull request.

**Comment by npisanti** [comment]
> When your audio device gets disconnected and then you try to connect to another audio device, the program throws an error when trying to close a stream what was disconnected, so I avoid this error by checking (externally) if the audio device is gone, then notifying the engine to not try to close it.

do you mean when your audio device get "physically" disconnected ?

> Perhaps there is a more foolproof way of handling this, like (inside the Engine code itself) checking the list of engines before closing the stream, oh, but you don't know what the previous audio device was when you are setting the engine up with a new audio device...

yes, this kind of thing should get managed directy by the engine. Actually i coded ofxPDSP just as a tool for creative coding, so connecting and changing devices wasn't an use case, but having an engine capable of doing it won't hurt.

**Comment by npisanti** [comment]
> > PS: i sent you a mail some time ago, have you seen it? i think we should find a better way to organize our efforts on ofxPDSP other than directly in the PR comments
> 
> Yes, I did see your email. Some really good thoughts, and I try to incorporate these things into the development of my own project and of ofxPDSP. I'm writing some unit-based sequencing code that could be good for ofxPDSP once it's done.
> 
> I'm sort of just changing things as needed for my own project, and if I think the changes apply to ofxPDSP as a whole, then I try to format everything nicely and submit a pull request.

i already did the unit sequencing stuff, now the default way of sequencing in pdsp is by using `pdsp::Function`. I updated the examples but i still have to deprecate the old stuff, i will keep it around for a while to avoid breaking old stuff. I will then move on on fixing the other things, probably later this year.

**Comment by npisanti** [comment]
> Yes, I did see your email. Some really good thoughts, and I try to incorporate these things into the development of my own project and of ofxPDSP. I'm writing some unit-based sequencing code that could be good for ofxPDSP once it's done.
> 
> I'm sort of just changing things as needed for my own project, and if I think the changes apply to ofxPDSP as a whole, then I try to format everything nicely and submit a pull request.

i already did the unit sequencing stuff, now the default way of sequencing in pdsp is by using `pdsp::Function`. I updated the examples but i still have to deprecate the old stuff, i will keep it around for a while to avoid breaking old stuff. I will then move on on fixing the other things, probably later this year.

**Comment by npisanti** [comment]
> Yes, I did see your email. Some really good thoughts, and I try to incorporate these things into the development of my own project and of ofxPDSP. I'm writing some unit-based sequencing code that could be good for ofxPDSP once it's done.
> 
> I'm sort of just changing things as needed for my own project, and if I think the changes apply to ofxPDSP as a whole, then I try to format everything nicely and submit a pull request.

i already did the unit sequencing stuff, now the default way of sequencing in pdsp is by using `pdsp::Function`. I updated the examples but i still have to deprecate the old stuff, i will keep it around for a while to avoid breaking old stuff. I will then move on on fixing the other things, probably later this year.

**Pull request closed without merging**
