### PR TITLE
Add methods to get MIDI in devices count and names

### PR DESCRIPTION
**Pull request by MacFurax**
Hi,

I have added methods to get number and names of MIDI In ports.
If you want to integrate it in your repo.

This my first pull request, not very sur how to do :-)

ADD: int getPortCount();
ADD: std::vector<std::string> getPortList();

### CODE REVIEW

**Comment by npisanti** [comment]
the code looks fine, i don't know about why it was marked as "draft" for github, it's not a problem that appveyor doesn't pass the build as i still have to fix it, i will merge it now

**Comment by MacFurax** [comment]
Concerning the Draft, it was the first time I made a pull request.
For "safety" I made it draft.
I don't known anything about appveyor.

Meanwhile I also add a module that bundle an OSC, ADSR, wave form switcher,
pulseWidth and detune.
I can make a pull request for it to.

By the way, thank's very mush for ofxPDSP !
It is just what I was looking for to learn audio synthetis, not to high
neither to low level.





Le jeu. 22 août 2019 à 16:37, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by npisanti** [comment]
please let me look at the code for that before! probably it isn't something minimal enough to have it in the `pdsp` core, for example i have a separate repo for my patches, synths and utility classes:

https://github.com/npisanti/np-patches

**Comment by MacFurax** [comment]
Here is the code

https://github.com/MacFurax/ofxPDSP/blob/master/src/modules/oscillators/ADSR_OSC.h
https://github.com/MacFurax/ofxPDSP/blob/master/src/modules/oscillators/ADSR_OSC.cpp

I don't really now how to name it.

I plane to make other modules like:

- Two OSCs, ADSRs to allow detuning on OSC
- Two OSCs, ADSRs, filters
- Two OSCs, ADSRs, LFOs, filters

I already have a look at np-patches.

I'm tempted to make a nodal synth builder. But not much time now.

Le jeu. 22 août 2019 à 22:36, Nicola Pisanti <notifications@github.com> a
écrit :

**Comment by npisanti** [comment]
it looks like a basic  OSC >> ADSR synth, with no filter, it isn't something minimal enough to stay into the pdsp core, it should stay in an external repo like my own synths and effects. 

Just modules that could have coarsely the same amount of functionality of a classic modular synthesizer module should go into the core ( no one-voice modules ! )

Cheers!

**Comment by MacFurax** [comment]
Okydo, I understand, I'll make my own lib/repo with them.

Cheers!

Le ven. 23 août 2019 à 15:08, Nicola Pisanti <notifications@github.com> a
écrit :

**Pull request merged**
